version: 1.0
provider:
  name: openfaas
  gateway: http://34.118.254.31:8080
functions:
  hello:
    lang: python3-http
    handler: ./hello
    image: europe-west1-docker.pkg.dev/firm-reason-462012-p9/functions/hello:latest

  generate2fa:
    lang: python3-http
    handler: ./generate2fa
    image: europe-west1-docker.pkg.dev/firm-reason-462012-p9/functions/generate2fa:latest

